os: linux
language: rust

cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

rust:
  - stable

script:
  - cargo build --verbose --all --locked
  - cargo test --verbose --all --locked

deploy:
  provider: cargo
  token: $OAUTH_KEY
  on:
    tags: true
