[package]
name = "escl-scan-gui"
version = "0.1.0"
authors = ["ElXreno <elxreno@gmail.com>"]
edition = "2018"

[dependencies]
gtk = { version = "0.8.0", features = ["v3_16"] }
gio = { version = "0.8.0", features = ["v2_44"] }
glib = "0.9.0"