[package]
name = "escl-scan-cli"
version = "0.1.1"
authors = ["ElXreno <elxreno@gmail.com>"]
repository = "https://github.com/ElXreno/escl-scan"
readme = "README.md"
license = "GPL-3.0"
keywords = [
    "escl",
    "scan"
]
categories = ["command-line-utilities"]
description = """
CLI for escl-scan
"""
edition = "2018"

[dependencies]
clap = "2.33.0"
scan = { package="escl-scan", path="../escl-scan" }
