name: "Build project with Nix"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - name: Building package
        run: nix build
      - name: Check package
        run: nix flake check
