name: "Build project with Nix"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: elxreno-rust
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Building package
        run: nix build
      - name: Check package
        run: nix flake check
