name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        rust: [stable, nightly]

    steps:
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.1
      with:
        rust-version: ${{ matrix.rust }}

    - name: Set up dependencies
      run: sudo bash -c "apt update && apt install libgtk-3-dev -y"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Build release
      run: cargo build --release --verbose

    - name: Strip release
      run: strip target/release/escl-scan-cli

    - name: Run tests
      run: cargo test --verbose

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: escl-scan-cli_rust-${{ matrix.rust }}-${{ matrix.os }}
        path: target/release/escl-scan-cli
